# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jakub/zad-5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jakub/zad-5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/zad-5/CMakeFiles /home/jakub/zad-5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jakub/zad-5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dronv1

# Build rule for target.
dronv1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronv1
.PHONY : dronv1

# fast build rule for target.
dronv1/fast:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/build
.PHONY : dronv1/fast

src/Bottom.o: src/Bottom.cpp.o

.PHONY : src/Bottom.o

# target to build an object file
src/Bottom.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Bottom.cpp.o
.PHONY : src/Bottom.cpp.o

src/Bottom.i: src/Bottom.cpp.i

.PHONY : src/Bottom.i

# target to preprocess a source file
src/Bottom.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Bottom.cpp.i
.PHONY : src/Bottom.cpp.i

src/Bottom.s: src/Bottom.cpp.s

.PHONY : src/Bottom.s

# target to generate assembly for a file
src/Bottom.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Bottom.cpp.s
.PHONY : src/Bottom.cpp.s

src/Propeller.o: src/Propeller.cpp.o

.PHONY : src/Propeller.o

# target to build an object file
src/Propeller.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Propeller.cpp.o
.PHONY : src/Propeller.cpp.o

src/Propeller.i: src/Propeller.cpp.i

.PHONY : src/Propeller.i

# target to preprocess a source file
src/Propeller.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Propeller.cpp.i
.PHONY : src/Propeller.cpp.i

src/Propeller.s: src/Propeller.cpp.s

.PHONY : src/Propeller.s

# target to generate assembly for a file
src/Propeller.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Propeller.cpp.s
.PHONY : src/Propeller.cpp.s

src/RotationMatrix.o: src/RotationMatrix.cpp.o

.PHONY : src/RotationMatrix.o

# target to build an object file
src/RotationMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/RotationMatrix.cpp.o
.PHONY : src/RotationMatrix.cpp.o

src/RotationMatrix.i: src/RotationMatrix.cpp.i

.PHONY : src/RotationMatrix.i

# target to preprocess a source file
src/RotationMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/RotationMatrix.cpp.i
.PHONY : src/RotationMatrix.cpp.i

src/RotationMatrix.s: src/RotationMatrix.cpp.s

.PHONY : src/RotationMatrix.s

# target to generate assembly for a file
src/RotationMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/RotationMatrix.cpp.s
.PHONY : src/RotationMatrix.cpp.s

src/Surface.o: src/Surface.cpp.o

.PHONY : src/Surface.o

# target to build an object file
src/Surface.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Surface.cpp.o
.PHONY : src/Surface.cpp.o

src/Surface.i: src/Surface.cpp.i

.PHONY : src/Surface.i

# target to preprocess a source file
src/Surface.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Surface.cpp.i
.PHONY : src/Surface.cpp.i

src/Surface.s: src/Surface.cpp.s

.PHONY : src/Surface.s

# target to generate assembly for a file
src/Surface.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Surface.cpp.s
.PHONY : src/Surface.cpp.s

src/Water.o: src/Water.cpp.o

.PHONY : src/Water.o

# target to build an object file
src/Water.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Water.cpp.o
.PHONY : src/Water.cpp.o

src/Water.i: src/Water.cpp.i

.PHONY : src/Water.i

# target to preprocess a source file
src/Water.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Water.cpp.i
.PHONY : src/Water.cpp.i

src/Water.s: src/Water.cpp.s

.PHONY : src/Water.s

# target to generate assembly for a file
src/Water.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/Water.cpp.s
.PHONY : src/Water.cpp.s

src/cuboid.o: src/cuboid.cpp.o

.PHONY : src/cuboid.o

# target to build an object file
src/cuboid.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/cuboid.cpp.o
.PHONY : src/cuboid.cpp.o

src/cuboid.i: src/cuboid.cpp.i

.PHONY : src/cuboid.i

# target to preprocess a source file
src/cuboid.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/cuboid.cpp.i
.PHONY : src/cuboid.cpp.i

src/cuboid.s: src/cuboid.cpp.s

.PHONY : src/cuboid.s

# target to generate assembly for a file
src/cuboid.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/cuboid.cpp.s
.PHONY : src/cuboid.cpp.s

src/gnuplot_link.o: src/gnuplot_link.cpp.o

.PHONY : src/gnuplot_link.o

# target to build an object file
src/gnuplot_link.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/gnuplot_link.cpp.o
.PHONY : src/gnuplot_link.cpp.o

src/gnuplot_link.i: src/gnuplot_link.cpp.i

.PHONY : src/gnuplot_link.i

# target to preprocess a source file
src/gnuplot_link.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/gnuplot_link.cpp.i
.PHONY : src/gnuplot_link.cpp.i

src/gnuplot_link.s: src/gnuplot_link.cpp.s

.PHONY : src/gnuplot_link.s

# target to generate assembly for a file
src/gnuplot_link.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/gnuplot_link.cpp.s
.PHONY : src/gnuplot_link.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/dronv1.dir/build.make CMakeFiles/dronv1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dronv1"
	@echo "... edit_cache"
	@echo "... src/Bottom.o"
	@echo "... src/Bottom.i"
	@echo "... src/Bottom.s"
	@echo "... src/Propeller.o"
	@echo "... src/Propeller.i"
	@echo "... src/Propeller.s"
	@echo "... src/RotationMatrix.o"
	@echo "... src/RotationMatrix.i"
	@echo "... src/RotationMatrix.s"
	@echo "... src/Surface.o"
	@echo "... src/Surface.i"
	@echo "... src/Surface.s"
	@echo "... src/Water.o"
	@echo "... src/Water.i"
	@echo "... src/Water.s"
	@echo "... src/cuboid.o"
	@echo "... src/cuboid.i"
	@echo "... src/cuboid.s"
	@echo "... src/gnuplot_link.o"
	@echo "... src/gnuplot_link.i"
	@echo "... src/gnuplot_link.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

